apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
    helm.sh/chart: {{ include "sabnzbd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          volumeMounts:
          - name: sabnzbd-config
            mountPath: /config{{ if .Values.claimNames.config.subPath }}
            subPath: {{ .Values.claimNames.config.subPath }}{{ end }}
          - name: sabnzbd-downloads
            mountPath: /downloads{{ if .Values.claimNames.downloads.subPath }}
            subPath: {{ .Values.claimNames.downloads.subPath }}{{ end }}
          livenessProbe:
            httpGet:
              path: /sabnzbd
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 300
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      securityContext:
        fsGroup: 1000
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: {{ .Values.claimNames.config.name }}
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: {{ .Values.claimNames.downloads.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
